### ISSUE TITLE
Current system sound IO

### ISSUE THREAD

**Issue by eofster** [64characters/Telephone#103]
There should be an option to keep using system default sound IO. So that when default is changed in the OS, Telephone would also use it instead of using the previously configured and still present IO.

**Comment by SteamedFish** [comment]
+1
I set Telephone to automatically start at system boot. It'll fallback to builtin if it starts before my bluetooth headphone connects, which is not what I want.

**Comment by kusmierz** [comment]
+1@eofster any chances to see this in the future?

**Comment by eofster** [comment]
It seems that what the majority wishes to be fixed here is not exactly this issue where Telephone has a setting to always follow sound IO selected in the System Preferences (I even don’t know yet if it is possible.) But rather the bug under the recent OS X versions when Telephone doesn’t automatically switch to the built-in sound IO when previously selected sound IO (like a headset) does not currently present and vice-versa, when a configured headset is disconnected. This must be fixed by the combination of #143 and #145.

**Comment by kusmierz** [comment]
@eofster, #143 and #145 are now fixed. Any chances to look at this, please?

**Comment by eofster** [comment]
@kusmierz could you describe your use case?

**Comment by kusmierz** [comment]
@eofster - normally I'm using my laptop as a... laptop (outside, in my home, etc), but I have also external LCDs, external soundcard, keyboard and mouse at the office (and I'm thinking about Thunderbolt dock/hub to connect it all by one cable), where I usually close the lid of my laptop an put it under the desk. So it appears as a desktop.

Anyway - I'm using internal soundcard when I'm at home or outside, and external soundcard (better DAC, etc) when I'm at the office.

You can also think about people using BT headset (which macOS sees as external devices) - it would be useful, especially for phone calls...

**Comment by eofster** [comment]
The situation when somebody’s using a preferred external device and expects a built-in device to be used when the external one is not connected should currently be covered. The following should also currently happen.

1. Device A is selected in Telephone’s sound preferences.
2. Device A is unplugged and not present in the system.
3. A call is established.
4. The built-in sound device is used.
5. Device A is connected again.
6. Telephone switches to device A automatically because it was selected before.

Or do you need automatic fallback from one non-built-in device to another non-built-in device?

**Comment by kusmierz** [comment]
Hm, indeed it changing devices as these are connected and works correctly. But in my mind, it is a little bit confusing, when there is no "system default" (such as ie. Skype has).

![image](https://cloud.githubusercontent.com/assets/404344/15958271/d982bfa6-2ef4-11e6-9cbc-5fe8627ba0e8.png)

Anyway - thanks, it works to me :)

**Comment by eofster** [comment]
Well, the logic was that you might want to use a specific preferred device for phone calls, regardless of what is currently configured by default in the system. And Telephone does its best to select this device for you when it’s available.

This worked, as far as I understand from the lack of negative reports, successfully since the early Telephone releases. But then it stopped working a couple of years ago because of the changes in the OS. And it now works again in the last Telephone releases.

**Comment by eofster** [comment]
So I’m closing this issue because I currently don’t see a specific use case for “always following the default IO selected in the OS.” At least nobody wished that. And all plus-ones above are actually the complaints to a regression that has been fixed, and not related to the original topic of this issue.

**Comment by eofster** [comment]
Reopening because people really stated asking specifically about following the IO selected in the system. Other apps apparently do this and that’s what people expect.
