### ISSUE TITLE
TCP transport support

### ISSUE THREAD

**Issue by printercu** [64characters/Telephone#107]
Hi! Thanks for great application!

Some time ago my sip provider changed settings, so that telephone stopped working correctly. Call is performed but there is absolute silence.

Same was on my android phone. They said to change "Transport type" to "TCP" (it was UDP) in advanced settings & this made it working again.

Do you plan to add this option to telephone?

**Comment by rtm-ctrlz** [comment]
Any news?

**Comment by eofster** [comment]
I’ve just discovered that it is already possible to make use of the TCP transport. It is already enabled in the user agent (which is not new) but isn’t chosen for the outgoing requests by default. To activate it for the outgoing requests, the proxy server should be configured with the addition `;transport=tcp` in the advanced account settings. For example:

```
[x] Connect using proxy
    Server: proxy.example.com;transport=tcp
```
