### ISSUE TITLE
Audio in seems broken

### ISSUE THREAD

**Issue by markusstoll** [64characters/Telephone#173]
I compiles Telephone from master^HEAD (3362e18369236689556de4ec7269c00dbb740731), with this version Audio in seems completely broken - I tested on multiple computers with multiple types of input
In each case, selection of all input devices seems to be normal, however, audio in is mute

**Comment by eofster** [comment]
Are you sure it’s not a coincidence? For example, when running the newer version from Xcode, the OS can present a firewall alert for Telephone and it’s easy to deny it. Or the network environment could change between the computer and the SIP server not allowing audio UDP packets to come in.

**Comment by markusstoll** [comment]
Hi,

i have the app store version of Telephone and my self compiled in direct comparison on multiple clients. 
Maybe its a question of

**Comment by markusstoll** [comment]
When I compile with all settings unchanged (just switched to compiling using my apple id) I still get no working Audio In.

When I switch off Sandboxing and recompile, Audio In and Out is not working.

I am not really familiar with current XCode and quite puzzled...

**Comment by eofster** [comment]
Closing this issue because it’s been several releases of the app, macOS, and Xcode since the original report. If you’re still experiencing this, please leave a comment and I’ll reopen it.
