### ISSUE TITLE
Log / history of calls

### ISSUE THREAD

**Issue by espen** [64characters/Telephone#26]
Would be nice if there could be a list of recent calls.

**Comment by hugohirsch** [comment]
+1 I'd love to see at least the time of the last call. Current functionality is that a window remains showing that a number called, but it does not show the time the call happened.

**Comment by gerritgriebel** [comment]
+1 Perfect implementation for my use would be a sqlite db which contails all call detail records, that's the way the way the Skype client does it. Based on that I have a small Go server which delivers calls as iCalendar entries for assigning call times to Jira Worklogs. Anyhow, sqlite would be the most simple way for me to archive the same with Telephone.

**Comment by eofster** [comment]
Sorry for keeping you waiting for so long. Call history is added in version 1.3.
