### ISSUE TITLE
Just pause iTunes and Spotify when call is accepted

### ISSUE THREAD

**Issue by klein0r** [64characters/Telephone#279]
At the moment it will be paused when it rings.

**Comment by Sija** [comment]
IMO it's the proper moment since you might miss the bell if the music is playing in the background.

**Comment by eofster** [comment]
Yes, it pauses when it rings exactly for the reason as @Sija described.

**Comment by klein0r** [comment]
Okay, the reason I've opened the issue is, that I'm working in a company and when someone is dials just "0", every phone in the company rings, even if the call is not for me.

**Comment by olku** [comment]
when someone is dials just "0", every phone in the company rings, even if the call is not for me.

I fail to see how this is a problem in the _app_.

**Comment by klein0r** [comment]
> I fail to see how this is a problem in the _app_.

Issue is solved, since it's over 5 years old and I don't work anymore in that company 😄 

Request was to pause the media player when the call is **accepted**, and **not when it rings**.
