### ISSUE TITLE
Always open windows on top on the same screen as the telephone application

### ISSUE THREAD

**Issue by klein0r** [64characters/Telephone#313]
When a new call comes in, the new caller window will be placed randomly anywhere on the screen - and maybe behind another application.

It would be nice when the new window will open next to the main window and in foreground if possible.

**Comment by eofster** [comment]
Is it displayed randomly for you? Telephone uses the standard macOS behavior when a call window appears on the same place you closed the previous call window. (If several call windows were open, on the place the last one was closed.) And if several call windows are being opened without closing the previous ones, they will be automatically cascaded. This is also a standard macOS behavior when every new window is be displayed to the right and bottom from the previous one just to keep the title of the previous one visible.

When an incoming call comes in, a standard macOS notification is used as a UI element that appears on top of everything and alerting the user. If you click it, Telephone becomes active and the incoming call window will be active inside Telephone, also enabling the standard hotkeys like `Command-Return` for accepting and `Command-.` for rejecting the call.

In addition to that, the next Telephone version 1.3 will allow you to answer a call right from the macOS notification.

**Comment by benrubson** [comment]
I also have an issue related to account windows.
Let's assume a MacBook connected to an external screen, lid closed.
I nicely put my windows one below the other.

Let's disconnect the screen an open the lid.
All the account windows will then be at the same place, one in front of the other.

Would be nice if all windows could keep their initial place.

Thank you 👍 

Ben

**Comment by klein0r** [comment]
🤷‍♂️
