### ISSUE TITLE
AddressBook calling in Sierra fails

### ISSUE THREAD

**Issue by neopaf** [64characters/Telephone#324]
URL is not parsed properly.
![2016-11-25 13 00 32](https://cloud.githubusercontent.com/assets/4362564/20621519/de9c9512-b30f-11e6-8bd8-993986d551c7.png)

(when calling from a small icon right of the phone -- works OK)

**Comment by eofster** [comment]
Well, this is not a valid `tel:` URI. A valid `tel:` URI doesn’t have slashes and spaces in it, for example: `tel:+1-234-567-8910`.

From [RFC 3966](https://tools.ietf.org/html/rfc3966#section-5.1.1):
> 5.1.1.  Separators in Phone Numbers
> [...]
> However, even though ITU-T E.123 [E.123] recommends the use of space
> characters as visual separators in printed telephone numbers, "tel”
> URIs MUST NOT use spaces in visual separators to avoid excessive
> escaping.

But I agree, if the system provides this way of making calls, the app should adapt to it.

How did you make that button to work at all :)? It is disabled for me. And are you sure it’s Maverics? It didn’t have such UI in the Contacts.app.

**Comment by eofster** [comment]
I’ve found how to make the button enabled. The checkbox ‘Calls from iPhone’ in *FaceTime* preferences needs to be checked and Telephone needs to be selected as ‘Default for calls.’

**Comment by neopaf** [comment]
If it's important, I'm mistaken on version. it's Sierra (10.12.1).

**Comment by eofster** [comment]
The pull request #386 adds the correction of `tel://` URIs into `tel:` URIs (because slashes are not part of the tel URI scheme). However, the stripping of whitespaces hasn’t been added yet. The solution for that would be to edit the phone number in the address book and to remove all spaces manually. After saving, the Contacts app should still display the formatted phone number.

**Comment by neopaf** [comment]
Wanted to check... but now in Address Book "call" button is not active :(

**Comment by eofster** [comment]
@neopaf I think, it is pretty weird when macOS makes that button active. It seems like you need to check the checkbox ‘Calls from iPhone’ in FaceTime preferences.

**Comment by neopaf** [comment]
got it. button became active... but no happiness :(

![2018-01-15 14 45 00](https://user-images.githubusercontent.com/4362564/34940955-b40fb3ca-fa02-11e7-8545-fef8107db693.png)

**Comment by eofster** [comment]
Could you try editing the contact and removing all spaces and parentheses from the phone number? After saving it, the Contacts app should still appropriately format the phone number, but at the same time Telephone should get the phone number string without additional characters.

What’s new in this version is that it should at least handle the `tel://` by converting it to the proper `tel:`.

**Comment by neopaf** [comment]
Done (though, it's a bit sad that one has to do that; maybe it's possible to auto-strip it?)
But still there's some junk there that stops happiness:
![2018-01-15 15 49 18](https://user-images.githubusercontent.com/4362564/34943197-b87f572c-fa0b-11e7-8068-121caa1c728c.png)

**Comment by neopaf** [comment]
(tried to resize window to see what else is there, but coudn't)

**Comment by eofster** [comment]
Thanks for the feedback, I’ll add the stripping.

**Comment by neopaf** [comment]
Thanks, Alexey.
Maybe you'll strip not only the "?part" but also this non-digits formatting junk too?

**Comment by eofster** [comment]
Yes, definitely.

**Comment by eofster** [comment]
Hmm, are you sure that you updated to version 1.3 and that the correct version is launched after you click that call button? To be sure, try clicking the button when the app is already running. The problem is that macOS sometime gets confused about which copy of the app to launch if there are multiple copies on the disk (including Time Machine backups).

I’ve just checked the sources and it turns out I’ve already added stripping of the parameter list (after ?).

**Comment by eofster** [comment]
The escaped characters (%20 instead of space) are not de-escaped, though. So, your original example would not work, but the last one, where you deleted the spaces, should work.

**Comment by neopaf** [comment]
It does. Thank you very much, Alexey.
![2018-03-26 16 08 46](https://user-images.githubusercontent.com/4362564/37908164-ffa7dc60-310f-11e8-9325-81968b0b9b22.png)


(большое спасибо!)
