### ISSUE TITLE
Answer process does not complete, so can't hang up

### ISSUE THREAD

**Issue by vibechild** [64characters/Telephone#35]
This problem occurs when receiving calls.  There are some cases (when connecting from another network over a VPN, at least) where the connection works, the decline/answer box pops up, and the answer button can be clicked to start two way audio, where things don't work quite right.

Clicking the decline button works as expected.

Clicking the accept button does not work as expected.  The call starts, and both sides can hear audio.  However, the decline/answer button is still there, and the ring tone is still being played.  The ring tone during the call is annoying, but the most inconvenient part is that the only way to hang up a call while the app is running is for the remote party to hang up. Pressing decline or closing the window both appear to hang up the call, but the remote party can still hear everything that is being said, with no indication of this on the local side.  This is a little dangerous for anyone who has something bad to say about the other party after hanging up.  The only way to stop audio is to close the program altogether.

Expected behavior would be for the answer button to switch to the "in call" mode, and allow the local party to hang up the call without the remote party continuing to hear.

**Comment by eofster** [comment]
Closing this issue because I haven’t heard complaints about this for a long time. If it still exists, please leave a comment and I’ll reopen it.
