### ISSUE TITLE
Sound input/output not working during call

### ISSUE THREAD

**Issue by Querschlag** [64characters/Telephone#374]
I use the AppStore version (1.2.6 - 126) and a headset attached via audio jack.

btw: The ringtone sample plays properly when changed it in the settings.

<img width="528" alt="screen shot 2017-07-17 at 18 59 35" src="https://user-images.githubusercontent.com/1651468/28279853-1e92778e-6b22-11e7-9e0a-e99ff1a4e582.png">
<img width="688" alt="screen shot 2017-07-17 at 18 59 29" src="https://user-images.githubusercontent.com/1651468/28279854-1e9d6fcc-6b22-11e7-93d4-59f0b81c48a2.png">
<img width="689" alt="screen shot 2017-07-17 at 18 59 18" src="https://user-images.githubusercontent.com/1651468/28279855-1ea4509e-6b22-11e7-990d-f5d0b739bd7c.png">

<img width="525" alt="screen shot 2017-07-17 at 19 00 37" src="https://user-images.githubusercontent.com/1651468/28279897-3f064374-6b22-11e7-8df2-7b0d3c86d7fb.png">
<img width="520" alt="screen shot 2017-07-17 at 19 00 29" src="https://user-images.githubusercontent.com/1651468/28279898-3f153294-6b22-11e7-9041-23376937b5d0.png">

**Comment by eofster** [comment]
This is usually a network-related problem rather than a problem with a sound device. Which SIP provider are you using? Did you receive SIP settings from it? Do the SIP provider’s instructions include information if a STUN server should be used? Do you know if your router or internet provider block some UDP ports? If it’s a laptop, can you try from another internet connection?

**Comment by Querschlag** [comment]
I use my fritz.box router as the sip server. I can initiate calls without a problem and I see when the receiver picks up, but apart from that I get no sound.
I have an active VPN connection, but that shouldn't be a problem since I'm connecting to a local IP address, right?
As far as I know there are no blocked outgoing ports on my router (UPnP is disabled).

**Comment by eofster** [comment]
Could you try without a VPN connection? Please also restart Telephone after stopping the connection.

Have you configured your account as follows, leaving all other account and network settings not checked by default?

Domain: fritz.box
Username: internal phone number (e.g. 620)
Password: password for the internal phone number
Use only G.711 codec: checked (Sound Settings)

**Comment by Querschlag** [comment]
Yeah this is definitely a VPN issue. Not quite sure why, but once I disabled it I got audio from the receiving end.
Thanks for your quick help.

**Comment by eofster** [comment]
This is an unfortunate historical downside of the SIP protocol. It explicitly specifies IP addresses in its requests, which under certain circumstances (in certain setups) can lead to confusions like this one, when probably an incorrect IP address is being chosen.

Please try specifying a STUN server in Telephone network settings. You can pick one from the list of the [public STUN servers](https://www.voip-info.org/wiki/view/STUN).
