### ISSUE TITLE
Telephone app will crash if the Spotify pause option is on when using Spotify

### ISSUE THREAD

**Issue by 1951FDG** [64characters/Telephone#392]
Hi,

Telephone app will crash if the Spotify pause option is turned on and when Spotify (latest) is running, 

_Temporary Solution_: Check Preferences of Telephone and turn off "Pause iTunes and Spotify during call"

Probably some safeguards are required, to prevent the crash also in the future, even if this feature is fixed now

**Comment by eofster** [comment]
Which versions of Telephone, macOS, and Spotify do you have? Cold you also include a crash log?

**Comment by 1951FDG** [comment]
Thanks for getting back this fast.

I just tested this on my system, and I can't reproduce the issue. The issue happened on a Macbook Air of a colleague of mine, running Mac OS X Yosemite.

The version of Telephone is 1.2.6
Spotify (1.0.65.320.gac7a8e02)
macOS : El Capitan 10.11.6

No problems on El Capitan

I believe the problem can be reproduced in Yosemite, where the version of Spotify may be older or different from the version on El Capitan or later. At the moment, I don't have access to a Yosemite system.

**Comment by eofster** [comment]
Thanks for the info. If possible, please check the Spotify version on that Mac with Yosemite.

**Comment by 1951FDG** [comment]
I will get back after two weeks time! H...
