### ISSUE TITLE
New release imminent?

### ISSUE THREAD

**Issue by mivale** [64characters/Telephone#406]
Hi,

The last release was over a year ago and 443 commits to master have been done since this release.

Any chance to see some shiny new features?

I, for one, would love to be able to call a script when I receive a call.

Kudos on the program. Nice and simple, clean interface

**Comment by eofster** [comment]
Yes, the release is around the corner and it’ll include the call history. The possibility of calling scripts on incoming calls will come right after that.

**Comment by mivale** [comment]
Oooh, wow. That's wonderful to hear.

Many thanks for your feedback!
