### ISSUE TITLE
App Nap

### ISSUE THREAD

**Issue by eofster** [64characters/Telephone#408]
The system applies App Nap to Telephone even when it’s in a call and the sounds gets distorted.

**Comment by RobFog** [comment]
Any chance you could slip this into 1.3? I think this is an issue that has kept me from consistently using Telephone.

**Comment by eofster** [comment]
@RobFog thanks for the feedback, I’ll include the fix into the 1.3.

**Comment by RobFog** [comment]
Wow, thanks! :-)
