### ISSUE TITLE
Start at login, hide from Dock, deny calls at notification and custom ringtone

### ISSUE THREAD

**Issue by dioobr** [64characters/Telephone#417]
Hi,

I would like to make four suggestions:

1. Option to start the app after login. I know it's possible to define this by the dock, but according to my second suggestion, an option in the preferences would be necessary;
2. Enable to hide the app, without showing the icon in the Dock;
3. Enable deny a call in the notification. Currently shows "Close" and "Reply". Even when you click "Close", the ringingtone continues;
4. Custom ringtone;

Great app. The best, no doubt.
Bye!

** macOS Sierra 10.12.6

**Comment by berlinbikerx** [comment]
You can use custom ringtones already:

Put your wav file into ~/Library/Sounds and choose it in Settings -> Sound/Audio

**Comment by eofster** [comment]
It is possible to decline the call from a notification. But because of macOS limitations, neither there can be a third button there not can the Close button be used to decline a call. The way it is possible now is to hold the Answer button which reveals the Decline button.

**Comment by eofster** [comment]
Thanks for the feedback. As discussed above, custom ringtones and declining calls from notifications are already supported. We already have an issue for the menu bar icon (#14) which implies the ability to hide the icon from the Dock. And I’ve just created an issue for enabling “start at login” in app preferences (#422).

**Comment by dioobr** [comment]
I used another software for some time and the way the notification was displayed was one of the good things. From my point of view, a third button seems unnecessary.
![screen shot 2018-01-19 at 12 40 27](https://user-images.githubusercontent.com/16680429/35156122-f9532338-fd16-11e7-933f-f256f728e857.png)

**Comment by eofster** [comment]
Hmm, I wonder how they did that. The first button means “Close” even if the title is different. And the app doesn’t get a callback when that button is clicked.

**Comment by eofster** [comment]
I see, there’s probably a [private method](https://stackoverflow.com/questions/38192389/detect-other-button-click-nsusernotification) for that, but we can’t rely on this, especially when being on the Mac App Store.

**Comment by dioobr** [comment]
I wasn't sure until you mention it, but I did a test here and in fact the "Decline" button declines the call, without showing any app windows.

**Comment by eofster** [comment]
Yep, this sounds like usage of that private method. The app just intercepts the Close button event and doesn’t get activated. Well, it would be good enough if that was a public method, but it’s not.

**Comment by dioobr** [comment]
I understand. I figured it was simpler.
Another thing, wouldn't it be interesting an indicator with the number of lost calls in the icon? Like what that appears in the Mail icon when you receive a new message.

**Comment by eofster** [comment]
Thanks for the idea, created issue #428.
