### ISSUE TITLE
call button in Address Book disabled

### ISSUE THREAD

**Issue by neopaf** [64characters/Telephone#418]
In #324 I had call button in Address Book app not working properly.
Not it is just completely disabled:

![2018-01-15 14 40 41](https://user-images.githubusercontent.com/4362564/34940807-14cfba62-fa02-11e7-9d0b-76bdfab9eeac.png)

![2018-01-15 14 41 36](https://user-images.githubusercontent.com/4362564/34940831-33f17250-fa02-11e7-95ea-813eebb82e53.png)

```
Обзор системного ПО:
  Версия системы:	macOS 10.13 (17A405)
```

**Comment by eofster** [comment]
Third-party apps don’t have access to those buttons. Please try to enabling the checkbox ‘Calls From iPhone’ in FaceTime preferences.

**Comment by neopaf** [comment]
> @neopaf I think, it is pretty weird when macOS makes that button active. It seems like you need to check the checkbox ‘Calls from iPhone’ in FaceTime preferences.

done that, button got active, thanks, Alexey!
