### ISSUE TITLE
G711, choose between ulaw and alaw

### ISSUE THREAD

**Issue by benrubson** [64characters/Telephone#432]
Hi,

Telephone gives the ability to force G711 codec.
Would be nice to be able to choose between ulaw and alaw versions of G711.

Many thanks 👍 

Ben

**Comment by benrubson** [comment]
Well, I close this as I managed to correctly "force" codec version on server side.
Feel free to re-open if needed.
Perhaps in a more large "select codec/order preferences" option ?
Thx 👍

**Comment by eofster** [comment]
Yes, I want to make it possible as part as #58, where it should be possible to select the specific codecs and their order.
