### ISSUE TITLE
Option to rewrite IP address in SDP

### ISSUE THREAD

**Issue by eofster** [64characters/Telephone#453]
It should be possible for the user to control the PJSIP account `allow_sdp_nat_rewrite` option. This will be useful when the computer has several network interfaces and PJSIP puts the IP address of another interface into SDP. This situation often happens when a VPN connection to a company network is used.

**Comment by devZer0** [comment]
i found that if you use hostname as domain and use vpn via viscosity, telephone app registers with wrong interface adress on pbx server . when i use the pbx's ip adress, the registration (check with "astersik -r"  -> "show sip peers") works ok and incoming calls will work (whereas with hostname, they don't).  the same behaviour exists when using hostname vs ip in x-lite softphone app, with the difference that x-lite won't work at all when using pbx hostname for domainname.
