### ISSUE TITLE
call drop after 30seconds

### ISSUE THREAD

**Issue by celevra** [64characters/Telephone#463]
Hi,

we are using freeswitch as sip server. After 30 seconds telephone closes the call, on the server log it looks like a normal bye.
freeswitch-users suggest to switch from udp to tcp but i can't finde a option in telephone.
Is it possible to switch to tcp?

regards

Celevra

**Comment by eofster** [comment]
Are you using the latest version 1.3.1?

Please try to disable the so-called codec locking by running the following command in Terminal when Telephone is stopped.

```
defaults write com.tlphn.Telephone LockCodec -bool NO
```

**Comment by celevra** [comment]
thank you for the fast answer, yes its 1.3.1 from the appstore
unfortunately lockcodec didn't helped

**Comment by eofster** [comment]
I’m going to ask you to provide more details about your setup. Please contact me at support@64characters.com.
