### ISSUE TITLE
Spotify is launched when you launch Telephone

### ISSUE THREAD

**Issue by justdave** [64characters/Telephone#531]
Even if I have the "pause iTunes and Spotify when phone rings" option disabled, it still launches Spotify when I launch Telephone.  Even with that option enabled, it should check if Spotify is already running or not, and only send the "I want to be able to control Spotify" request if it's already running.  If it's not running, there's no point in trying to pause it. :-)  If that option is disabled, don't bother sending the request at all.  It can be sent when you enable the option if the app launched with it disabled.  I have Spotify and don't use it that often, so it's annoying to have it get launched every time I run Telephone and just have to quit it again.

**Comment by eofster** [comment]
This is a problem of macOS sandboxing. I guess your Spotify is located in a directory other than the standard /Applications directory. The solution is to move it there.

Telephone checks if Spotify is running before trying to pause it. But the problem happens long before that. At the very early stage during app launch when Telephone just tries to obtain a reference to the Spotify app to control it later, macOS launches Spotify if it is located not in a standard applications directory.
