### ISSUE TITLE
no preloaded routes 

### ISSUE THREAD

**Issue by mschering** [64characters/Telephone#532]
When I try to call I get the error "no preloaded routes". What could this be?

**Comment by eofster** [comment]
This sounds like something provider-related. Have you already tried contacting your phone provider or administrator?

**Comment by mschering** [comment]
Yes sorry for bothering. It seems they’re blocking all outbound calls and they can turn that off.

**Comment by mschering** [comment]
Sorry it still doesn't work I can do outbound calls with another voip client Zoiper. I don't know why I can't do outbound calls with Telephone. I'd prefer to use Telephone because it's much cleaner in design. Good job!

**Comment by eofster** [comment]
If it works in another app, we should also make it work in Telephone. We just need to find a configuration that your provider expects. I’ll need to ask you some details that you probably wouldn’t want to share publicly, so please write me to support@64characters.com.

**Comment by eofster** [comment]
The problem was in the `Route` header that is inserted according to standard when the proxy is configured for the account and all SIP requests are routed through it. The solution was to suppress this header by configuring the proxy server like this: `proxy.example.com;hide`.
