### ISSUE TITLE
Ignore URI parameters for reachability

### ISSUE THREAD

**Issue by eofster** [64characters/Telephone#534]
When the proxy server is configured with a parameter like `;hide`, the reachability-based network detection doesn’t work. Such parameters must be ignored before using the hostname in the reachability API.

**Comment by mschering** [comment]
When do you think this will make it into a release?

**Comment by eofster** [comment]
I’m sorry, I don’t know yet. Definitely not this year.

**Comment by eofster** [comment]
Does this problem still exist? I looked into it and found out that my original assumption was probably wrong. The proxy server isn’t used in the reachability API that triggers reconnection. It’s only the registrar host that is being used there, but that one doesn’t usually have any parameters.

**Comment by mschering** [comment]
Well, it did work back then. But in the meantime the provider switched to another platform where it's no longer necessary. So maybe the problem is very rare.
