### ISSUE TITLE
Call Transfer failed because lacking hook-flash(SIP INFO)

### ISSUE THREAD

**Issue by phoenixwu** [64characters/Telephone#537]
My SIP provider needs ue to send a SIP INFO event to emulate hook flash before sending call transfer invite.

that SIP INFO must contains a header with "c: application/hook-flash"
and SDP with "Signal=hf"

Is it possible to implement as an option of Telephone.app?

**Comment by eofster** [comment]
Does your provider still require it? Which provider is that?
