### ISSUE TITLE
Not receiving audio due to wrong IP address

### ISSUE THREAD

**Issue by jomo** [64characters/Telephone#538]
I'm connected to two networks:

Home network:
- Gateway: 192.168.0.1 (router.local)
- Own IP: 192.168.0.2

VPN Network:
- Gateway: 10.0.0.1
- Own IP 10.0.0.2

The VPN gateway is my default gateway.

I have a SIP account on my home router, basically `user@router.local`. SIP packets are sent from `192.168.0.2` to `192.168.0.1` and vice-versa, but the `Via` and `Contact` headers use `10.0.0.2`.

Using `router.local` as a proxy doesn't seem to make a difference.

Sending audio works fine, and as soon as I disable my VPN (i.e. the home router becomes the default gateway), receiving audio works as well.

**Comment by eofster** [comment]
If the SIP server on the router is running Asterisk, this SIP account configuration can solve the problem:
```
nat = force_rport,comedia
```
If not, an option to rewrite IP address in SDP (#453) should overcome this problem on the app side.

**Comment by eofster** [comment]
Fixed in #556. One should check the new checkbox “Update IP address”.
