### ISSUE TITLE
Active call volume controls

### ISSUE THREAD

**Issue by pjv** [64characters/Telephone#54]
in case anyone is interested, i just pushed a [commit](https://github.com/pjv/Telephone/commit/9ceabc68a72461dcbec346961673ec35fd3952b5) to my fork of telephone that implements simple volume / mic level controls in the active call window.

i use telephone with a USB headset which is NOT my default sound output device. this makes it pretty awkward to adjust the volume when a call comes in -- i have to go fumbling around in the sound preference pane which is hard to do when i am talking to someone.

![screenshot](https://img.skitch.com/20120404-j68jr478e2ndy32bi1x95w77hf.png)

so i did a quick and dirty addition to put these slider controls in the active call window. the implementation is probably pretty ugly and undoubtedly won't cover a lot of potential sound devices since i have only the one to test with. that said, it is working with my headset and i thought i would throw it out to you all in case anyone else wants to try it and/or improve the implementation.

if you are interested in incorporating this change into the master project, but want changes to the way i implemented it, let me know and i'll work on it and then send a pull request. 

if i get inspired, the next refinement i'll make is making that lower part of the window hide-able with a little hide/reveal triangle so people who don't want to mess with the volume don't have to see the controls.

**Comment by jecarroll** [comment]
I've just paid annual patronage on the Telephone app and my sole complaint with the app is this inability to control the volume of the call when using my USB headset (which is NOT my default sound output device). Hope you can fix!

**Comment by markdegrootnl** [comment]
+1

**Comment by luckman212** [comment]
Is there any way this can be merged? @pjv  (I know it was 8 years ago) but did you submit a PR?

**Comment by pjv** [comment]
sorry @luckman212, nobody ever expressed interest and i never submitted a PR. i haven't used this app in a long, long time and I'm no longer doing active macos development so haven't kept up to date with audio device API changes. I'd be surprised if that old code still works. but my fork is still sitting there with the commit linked above if anyone wants to play with it.

**Comment by luckman212** [comment]
@pjv ok, thanks anyway for the reply.
