### ISSUE TITLE
Call Transfer failed Mac OS

### ISSUE THREAD

**Issue by ottopic** [64characters/Telephone#541]
Hello,
during call, if I transfer the call to other number I hear calling in my ears and recipient answer to me not to transferring call.

Thank you

**Comment by eofster** [comment]
If I understood you correctly, this is expected and this is how attended call transfer works. First you call a person you want to transfer to. They reply, you talk to them and click the transfer button, which disconnects you from the call and connects the original person you were talking to with the one you wanted to transfer them to. Isn’t this what you expect? Or does it not work that way?
