### ISSUE TITLE
tel: links not working

### ISSUE THREAD

**Issue by nQk2** [64characters/Telephone#543]
Hi,
I've set the tel: protocol handler to Telephone.app using RCDefaultApp.
When I open a tel: link, Telephone opens, but doesn't start a call.
How do I fix that?

**Comment by eofster** [comment]
Do you still have this problem and could you give me an example of a tel: link you’re using?

**Comment by designorant** [comment]
> I've set the tel: protocol handler to Telephone.app using RCDefaultApp.

@nQk2 Not really related to your issue but you don't need RCDefaultApp if `tel:` is your only concern and you have FaceTime app on your system (see: FaceTime → Preferences → Settings → Default for calls).
