### ISSUE TITLE
Problem making call by Contacts app

### ISSUE THREAD

**Issue by matteovg7** [64characters/Telephone#554]
Hi,
I have some problem making call by Contacts app. I followed the guide in the page https://www.64characters.com/telephone/faq but the call icon in Contacts app is always disabled.
I set Telephone as default app for call in FaceTime but I don't have an iPhone so i don't have the checkbox "Calls from iPhone".
Can be this the problem?
I have macOS Catalina 10.15.1.

Thank you.
Matteo

**Comment by eofster** [comment]
Yes, I think that’s the case. macOS seems to enable those buttons when the “Calls from iPhone” checkbox is active. At least I haven’t seen other ways yet.

**Comment by matteovg7** [comment]
Ok, thank you.
Unfortunately in Italy call over WiFi are not supported so we can't enable this feature.
Thanks anyway.
