### ISSUE TITLE
Create iOS version, with Push Notifications

### ISSUE THREAD

**Issue by libertyforall1776** [64characters/Telephone#56]
There is a need for a good, free iOS SIP VoIP client with Push Notifications to truly implement phone like features with incoming call notifications on iPad/iPod Touch especially.

**Comment by akhilcb** [comment]
This would have been a great feature. Any plans for the same?

**Comment by drale2k** [comment]
Any update on this? Can not find a single decent iOS SIP client :/

**Comment by suderman** [comment]
I've been using Groundwire on iOS with push notifications. Not as simple as Telephone on OS X but it's been working great for me.

**Comment by drale2k** [comment]
@suderman  I need an OS app so i can modify it

**Comment by suderman** [comment]
@drale2k That would be a nice find!

**Comment by richrines** [comment]
An iOS app would be awesome! Did you ever get around to working on one @eofster?

**Comment by eofster** [comment]
The Mac app is still getting all of my attention, but all new code is being written for both platforms: macOS and iOS.

**Comment by eofster** [comment]
Closing this issue, because “make an iOS app” is a whole project on itself, not just a feature of the current one.
