### ISSUE TITLE
How to dial and call to an extension number ?

### ISSUE THREAD

**Issue by diegomgarcia** [64characters/Telephone#563]
Hello guys I've tried to call to a customer that has PBX system but I couldnt find a way to type the extension number so every time I've to wait to until some attendant pick the fone and transfer to that extension number ...

Is there any function or way to do that ?

**Comment by eofster** [comment]
There’s no UI keypad in the app, but it is till possible to send tone signals. You need to press numeric keys on your Mac keyboard when a call window is active. The call window is the one that temporary appears for the duration of a call and where you see call time ticking. It doesn’t have any text fields, but it still reacts to hotkeys like numeric key presses, H for hold, M for mute, and T for transfer.

**Comment by diegomgarcia** [comment]
Ok thanks, I will try that.

**Comment by eofster** [comment]
I’m closing the issue, but feel free to comment if you’re still having troubles.
