### ISSUE TITLE
Add Touch Bar functionality

### ISSUE THREAD

**Issue by CyrusOmerta** [64characters/Telephone#585]
Accept/end calls on the  Touch Bar,  transfer, hold or mute calls. Tried doing a few  basic  commands on BetterTouch tool but  made little progress.

**Comment by olku** [comment]
Propose to close because apple discontinued the touchbar. There are already keyboard shortcuts.

**Comment by eofster** [comment]
As mentioned above, closing this issue because Apple discontinued Touch Bar.

**Comment by CyrusOmerta** [comment]
Sad to see this feature delayed then killed. I bought another app to
implement touchbar functionality.


Kind Regards,
Marchand Brink
