### ISSUE TITLE
Disconnected constantly

### ISSUE THREAD

**Issue by mschering** [64characters/Telephone#641]
I don't know if it's an issue with the app or with the provider. But since last week I'm constantly disconnected and I have to relogin. 

I tried another app now and the problem doesn't occur with that one. 

I like the cleanliness of Telephone but this problem is a show stopper. Maybe you have som suggestions?

Thanks,
Merijn

**Comment by olku** [comment]
Probably resolved already but this is most likely a local network issue (99,9% of such symptoms are) or some problem at your internet or VoIP SIP provider, not an app issue.

**Comment by eofster** [comment]
If it still needs attention, feel free to comment and I'll reopen the issue.
