### ISSUE TITLE
Immutable character set passed to mutable function

### ISSUE THREAD

**Issue by dotsam** [64characters/Telephone#667]
Hi there! Thanks for your work on Telephone! In a field of weird cross-platform Java and GTK SIP clients, it's nice to find one that's native to the Mac and not bloated with weird features or a crazy UI.

Telephone is one of the last Intel binaries running on my M1 Mac, so I decided to build it from source myself to get a native Apple Silicon version. After doing this, I hit a bug while dialing a star code extension (`*43` in this case):

```
void CFCharacterSetAddCharactersInString(CFMutableCharacterSetRef, CFStringRef): Immutable character set passed to mutable function
```

Which is being thrown from line 230 here: https://github.com/64characters/Telephone/blob/d13b7d1d4497e6a009907d751962c8851f4f4fdd/Telephone/AKTelephoneNumberFormatter.m#L219-L231

My fix has been to either initialize `phoneNumberCharacterSet` directly as a `NSMutableCharacterSet` or to make it a `mutableCopy` of `NSCharacterSet` rather than just a `copy`. Either seems to work, but I'm not sure what the advantages/disadvantages are of the different approaches.

**Comment by eofster** [comment]
Oh wow, thank you! I wonder how it's been working all these years, since 2008!

**Comment by eofster** [comment]
Same problem – allocating `NSCharacterSet` and assigning it to an `NSMutableCharacterSet` variable – is in the `AKSIPURIFormatter`.
