### ISSUE TITLE
Wrong Data

### ISSUE THREAD

**Issue by Joker000110** [64characters/Telephone#668]
Hello, i downloaded the App on the App Store and entered wrong information when registering. Unfortunately, even after deleting the app, I can no longer change the wrong data. How does that work or can I delete the data?
Kind Regards

**Comment by gsbabil** [comment]
Hi @Joker000110, 

You can try updating/deleting the relevant `"application password"` entries from the `login` key-chain using Mac's `Keychain Access` app. The following steps might help:

- Open `Keychain Access`
- Select `Default Keychains > login` in the left-hand side bar
- Now search for `SIP:` using the search-bar in the top-right corner
- Delete/modify the entries you need

Hope this helps. Thanks.

**Comment by eofster** [comment]
@Joker000110 contrary to iOS, in macOS, deleting the app doesn't delete its settings. You can change settings in the app preferences. In the main menu on the very top of the screen select Telephone > Preferences... Then switch to the Accounts tab and uncheck the "Use this account" checkbox. After changing account settings, check the checkbox again to save them.
