### ISSUE TITLE
Incoming call address wrong

### ISSUE THREAD

**Issue by MACscr** [64characters/Telephone#73]
Not 100% sure how to describe this, but with Freeswitch and blue.box, it supports multi-tenant support by using domain names. So a user would be something like 500@foo.com. Registration with Telephone seems to work fine with this as you just enter the server name as foo.com, then user as 500, then the password. The problem is that when I receive an incoming call and miss it or whatever, the call comes in as +15555555555@ip instead of @foo.com. So when i try to hit the redial option on that window, it then calls the server as 500@ip for some odd reason. Thus my call fails authentication. Any ideas why that might be and how we can resolve this?

**Comment by fulldecent** [comment]
@MACscr Is this the same issue you are referring to?

**Comment by eofster** [comment]
I’m closing this because it could have been fixed by #185 and there has been no follow-up from the author of this issue. And the problem described by @fulldecent should be handled in #425.
