### ISSUE TITLE
Two SIP accounts, only one goes "Available" on application start

### ISSUE THREAD

**Issue by reinvented** [64characters/Telephone#77]
I have two SIP accounts defined: one is my local Asterisk server, the other a third-party VOIP provider. Both accounts are working without issue otherwise.

On application start only the first account connects automatically; the second account needs to be toggled manually from "Unavailable" to "Available" in the UI; it won't go online automatically.

![two-pbx-one-online](https://f.cloud.github.com/assets/328524/723451/3bd12780-e018-11e2-8c1f-f57d71177f25.png)

**Comment by RobFog** [comment]
Should the milestone be removed?
