### ISSUE TITLE
Feature Request: Callto Links

### ISSUE THREAD

**Issue by lukaseppler** [64characters/Telephone#8]
Awesome little program, I love it (bought it with Appstore). I would love it to handle callto:// links like skype does.

**Comment by lksnmnn** [comment]
Still not working. Pipedrive is using `callto` instead `tel`.

**Comment by Sija** [comment]
@lksnmnn perhaps you should create an issue at _Pipedrive_ issue tracker instead.

**Comment by lksnmnn** [comment]
I wrote them. We will see what happens, but would it hurt to add the scheme? I can try to do it myself. If it works I will create a PR.

**Comment by lksnmnn** [comment]
I forked the project and added `callto` as an URI scheme, but Chrome prevents it from being handled by any other app than Skype. Cheers.

**Comment by bertrand-lupart** [comment]
You can use the RCDefaultApp preference panel for assigning callto: links to Telephone.app
http://www.rubicode.com/Software/RCDefaultApp/

**Comment by eofster** [comment]
In the meantime, I created a [small utility](https://github.com/64characters/CalltoBouncer/) that should solve this problem. The utility responds to the `callto` URLs, turns around and opens the `tel` URLs.

[Download](https://github.com/64characters/CalltoBouncer/releases/download/1.0/CalltoBouncer-1.0.zip)

You might need to change the `callto` URL handler to this utility via the [RCDefaultApp](http://www.rubicode.com/Software/RCDefaultApp/) preference pane. Please tell me if it works for you.
