### ISSUE TITLE
'Call back' button calls a different number

### ISSUE THREAD

**Issue by gozzilli** [64characters/Telephone#98]
I have a problem that made me spend quite a lot of money. 
When a person in my address book calls me from their voip account and I use the 'Call back' button to redial, the call goes to a different phone (I think it's her mobile phone, also in the address book under the same name) instead of the voip account she called from, causing me to spend money without realising. 

I'm expecting the call to go to xxx@sip.messagenet.it, but it doesn't. I'm not sure how to check where it's going, if you can tell I'm happy to check. 

![bug](https://f.cloud.github.com/assets/1502267/2120337/49544d0e-91ae-11e3-8fbc-3129a45e22ac.PNG)

**Comment by benrubson** [comment]
For me the 'Call back' button does not work, call times-out.
Status says "calling..." then "Request Timeout".
Is it because I do not use the usual SIP port but another one ? Perhaps it's a clue...

Thx !

Ben

**Comment by eofster** [comment]
@gozzilli Davide, I’m sorry for the inconvenience and thank you for reporting this problem.

**Comment by eofster** [comment]
@gozzilli is it possible that these two numbers have the same last 10 digits and only area code is different? Or are these numbers completely different?

**Comment by gozzilli** [comment]
@eofster this is now quite old (about 2 years) and I'm not sure it still happens. However I'll try to test it again.

What was happening was the following:
1. Person A calls me on my voip number from her voip number. Her number appears as <number>@<voip-provider.com> where voip-provider.com is our voip provider (both mine and hers). 
2. Call ends, window remains open. I click on the redial button (see screenshot above).
3. The call goes to Person A's phone number (her mobile phone), which is the default in my address book, instead of going to her voip number <number>@<voip-provider.com> where she was calling me from. The two numbers are completely different

Hope this helps, 
Davide

**Comment by eofster** [comment]
Thank you for the clarification Davide! If you’re able to get more details on this, that would be highly appreciated.

**Comment by eofster** [comment]
Could be fixed in #185.
